name: publish-nuget-package
on:
  push:
    branches:
    - main
    - master
    - feature/**
    
jobs:
  calculate-version:
    name: Calculate Version
    runs-on: ubuntu-latest
    env:
      LBHPACKAGESTOKEN: ${{secrets.LBHPACKAGESTOKEN }}
    outputs:
      version: ${{ steps.gitversion.outputs.nuGetVersionV2 }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.7
        with:
          versionSpec: '5.x'
      - name: Determine package version
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0.9.7
        with:
          useConfigFile: true
      - name: Display package version
        run: |
          echo "Version: $GITVERSION_NUGETVERSIONV2"

  check-code-formatting:
    name: Check code formatting
    runs-on: ubuntu-latest
    needs: calculate-version
    env:
      LBHPACKAGESTOKEN: ${{secrets.LBHPACKAGESTOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dotnet format
        run: dotnet tool install dotnet-format --tool-path ./dotnet-format-local/
      - name: Run formatter check
        run: ./dotnet-format-local/dotnet-format --check

  build-and-test:
    name: Build & Test
    runs-on: ubuntu-latest
    needs: calculate-version
    env:
      LBHPACKAGESTOKEN: ${{secrets.LBHPACKAGESTOKEN }}
    outputs:
      version: ${{ needs.calculate-version.outputs.version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: docker-compose build hackney-shared-processes-test
      - name: Run tests
        run: docker-compose run hackney-shared-processes-test

  publish-package:
    name: Publish Package
    runs-on: ubuntu-latest
    needs:
     - build-and-test
     - check-code-formatting
    env:
      VERSION: ${{ needs.build-and-test.outputs.version }}
      LBHPACKAGESTOKEN: ${{secrets.LBHPACKAGESTOKEN }}
      NUGET_DEPLOY_KEY: ${{secrets.NUGET_DEPLOY_KEY }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build the Package
        run: dotnet pack Hackney.Shared.Processes -p:PackageVersion=$VERSION --configuration Release
      - name: Publish the Package
        run: |
          cd Hackney.Shared.Processes/bin/Release
          dotnet nuget push Hackney.Shared.Processes.*.nupkg -s https://nuget.pkg.github.com/LBHackney-IT/index.json --api-key ${{secrets.NUGET_DEPLOY_KEY }}